name: publish_and_replay_subject_example
description: "The example of a chat using PublishSubject and ReplaySubject."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: 0.28.0
  
dev_dependencies:
  surf_lint_rules: 3.1.0

flutter:
  uses-material-design: true
